=== vkouvari/ergasia/kanones.dtd
<!ELEMENT TEI.2 (teiHeader, text)>
<!ELEMENT teiHeader (fileDesc)>
<!ELEMENT fileDesc (titleStmt, publicationStmt)>
<!ELEMENT titleStmt (title, author)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT publicationStmt (publisher, address, date)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT address (settlement)>
<!ELEMENT settlement (#PCDATA)>
<!ATTLIST settlement
          type CDATA #REQUIRED>
<!ELEMENT date (#PCDATA)>
<!ELEMENT text (body)>
<!ELEMENT body (entry+)>
<!ELEMENT entry (form, xr?, gram?, etym?, def?, bibl?, etm?, sense*)>
<!ELEMENT form (orth)>
<!ELEMENT orth (#PCDATA)>
<!ELEMENT gram (#PCDATA)>
<!ELEMENT etym (#PCDATA)>
<!ELEMENT sense (bibl | def | cit | bibil | usg | q)+>
<!ELEMENT def (#PCDATA)>
<!ELEMENT bibl (#PCDATA)>
<!ELEMENT xr (lbl, ref)>
<!ATTLIST xr
          type CDATA #REQUIRED>
<!ELEMENT lbl (#PCDATA)>
<!ELEMENT ref (#PCDATA)>
<!ELEMENT cit (bibil?, bil?, bible?, bibl*, q+)>
<!ELEMENT q (#PCDATA)>
<!ELEMENT etm (#PCDATA)>
<!ELEMENT usg (#PCDATA)>
<!ATTLIST usg
          type CDATA #REQUIRED>
<!ELEMENT bibil (#PCDATA)>
<!ELEMENT bil (#PCDATA)>
<!ELEMENT bible (#PCDATA)>

=== vkouvari/ergasia/tei-encoding.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TEI SYSTEM "C:\Users\paraskevoula\Desktop\ergasia\kanones.dtd">
<TEI.2>
    <teiHeader>
        <fileDesc>
            <titleStmt>
                <title>Greek lexicon of the Roman and Byzantine periods</title>
                <author>Σοφοκλής Ευαγγελινός Αποστολίδης,</author>
            </titleStmt>
            <publicationStmt>
                <publisher>Oxford University Press</publisher>
                <address>
                    <settlement type="city">Cambridge</settlement>
                </address>
                <date>1914</date>
            </publicationStmt>
        </fileDesc>
    </teiHeader>
    <text>
        <body>
            <entry>
                <form>
                    <orth>καινοειδής,</orth>
                </form>
                <gram>ές</gram>
                <etym>ΕΙΔΩ</etym>

                <sense>
                    <def>novel, new.</def>
                    <bibl>Orig. I, 1540 C.</bibl>
                </sense>
            </entry>

            <entry>
                <form>
                    <orth>Καΐνοί</orth>
                </form>
                <xr type="syn">
                    <lbl>see</lbl>
                    <ref>Καΐανοί</ref>
                </xr>
            </entry>

            <entry>
                <form>
                    <orth>καινολογία</orth>
                </form>
                <gram>, ας, ἡ,</gram>
                <etym>καινολόγος</etym>
                <sense>
                    <def>new mode of expression, strange language.</def>
                    <bibl>Polyb. 88, 1, 1.</bibl>
                    <bibl>Dion. H. V, 458, 1.</bibl>
                    <bibl>Strab. 1, 2, 8.</bibl>
                    <bibl>Plut.  II, 1068 D.</bibl>
                </sense>
            </entry>

            <entry>
                <form>
                    <orth>καινοπαθέω</orth>
                </form>
                <gram> ήσω</gram>
                <sense>
                    <def>καινόν τι πάσχω.</def>
                    <bibl>Plut, II, 1106 A.</bibl>
                </sense>
            </entry>

            <entry>
                <form>
                    <orth>καινοποιία</orth>
                </form>
                <gram>, ας, ἡ,</gram>
                <etym>καινοποιός</etym>
                <sense>
                    <def>mutation, change.</def>
                    <bibl>Polyb. 4, 2, 10.</bibl>
                </sense>
            </entry>

            <entry>
                <form>
                    <orth>καινοποιός</orth>
                </form>
                <gram>, ἆ, ὀν,</gram>
                <etym>ποιέω</etym>
                <sense>
                    <def>renovating.</def>
                    <bibl>Greg.  Naz. II, 608 D, πνεῦμα.</bibl>
                </sense>
            </entry>

            <entry>
                <form>
                    <orth>καινοπραγία</orth>
                </form>
                <gram>, ας.  ἡ,</gram>
                <etym>πράσσω</etym>
                <sense>
                    <def> innovation</def>
                    <bibl>Polyb. 9, 22, 5, intrigue.</bibl>
                    <bibl>Diod. 15, 8.</bibl>
                </sense>
            </entry>

            <entry>
                <form>
                    <orth>καινοπρεπής</orth>
                </form>
                <gram>, ές,</gram>
                <etym>πρέπω</etym>
                <sense>
                    <def>novel, strange.</def>
                    <cit>
                        <bibl>Plut.  Il, 334 C.</bibl>
                        <bibl>Method. 385 B</bibl>
                        <q>To καινοπρεπές τοῦ θαύματος.</q>
                    </cit>
                </sense>

                <sense>
                    <bibl>Phot. III, 249</bibl>
                    <def> A, λέξεις, new flanged words.</def>
                </sense>
            </entry>

            <entry>
                <form>
                    <orth>καινός</orth>
                </form>
                <gram>, ή, όν, πειυ.</gram>

                <sense>
                    <def>Καινὸς ἄνθρωπος, the Ro man novus homo.</def>
                    <bibl>Plut. 1, 336 B. App. II, 176, 31.</bibl>
                </sense>
            </entry>

            <entry>
                <form>
                    <orth>καινόσπουδος</orth>
                </form>
                <gram>, ον</gram>
                <etym>σπουδή</etym>
                <sense>
                    <def> fond of novelty.</def>
                    <cit>
                        <bibl>Patriarch. 1105 B.</bibl>
                        <bibl>Longin. 5, 1 1</bibl>
                        <q> το καινόσπουδον. fondness for novelty.</q>
                    </cit>
                </sense>
            </entry>

            <entry>
                <form>
                    <orth>καινοτομητέον</orth>
                </form>
                <sense>
                    <def> δεῖ καινοτομεῖν.</def>
                    <bibl>Athen. Mech. 3.</bibl>
                </sense>
            </entry>

            <entry>
                <form>
                    <orth>καινότροπος</orth>
                </form>
                <gram>ον,</gram>
                <etym>τρόπος</etym>
                <def> new-fashioned.</def>
                <bibl> App. 1, 750, 47.</bibl>
            </entry>

            <entry>


                <form>
                    <orth>καινούργιος</orth>
                </form>
                <gram> , α, ον, </gram>
                <etym>καινουργός</etym>
                <sense>
                    <def> new</def>
                    <bibl>Aet. 8, 6 p. 150 b, 50</bibl>
                    <q>χύτρα</q>
                    <bibl>Theoph. 686, 19.</bibl>
                </sense>
            </entry>

            <entry>
                <form>
                    <orth>καινουργός</orth>
                </form>
                <gram>, όν</gram>
                <etm>ΕΡΓΩ</etm>

                <sense>
                    <def>making new, innovating.</def>
                    <bibl>Pseudo-Jos. Macc. 11.</bibl>
                </sense>

                <sense>
                    <def>Newly made, new</def>
                    <bibl>Lucian. I, 27.</bibl>
                    <usg type="syn">καινούργιος</usg>
                </sense>
            </entry>

            <entry>
                <form>
                    <orth>καινοφωνία.</orth>
                </form>
                <gram>ας, ή,</gram>
                <etym>φωνή</etym>
                <sense>
                    <def>novelty of sound, simply novelty.</def>
                    <bibl>Apollon. Ephes. 1384</bibl>
                    <bibl>A.Eust. Mon. 905 A.</bibl>
                </sense>
            </entry>

            <entry>
                <form>
                    <orth>καίνωσις</orth>
                </form>
                <gram>, εως, ἡ,</gram>
                <etym>καινόω</etym>
                <sense>
                    <def>innovation.</def>
                    <bibl>Philon ΙΙ, 45,47.</bibl>
                    <bibl>Jos. Ant. 18, 6, 10, p. 896.</bibl>
                </sense>
            </entry>

            <entry>
                <form>
                    <orth>καιρικός</orth>
                </form>
                <gram>ή, όν</gram>
                <etym>καιρός</etym>
                <sense>
                    <def> of time: of a season.</def>
                    <bibl>Ptol. Tetrab. 76. 136.</bibl>
                    <bibl>Galen. II, 362 D,in the critical time.</bibl>
                </sense>
            </entry>

            <entry>
                <form>
                    <orth>καιρολουσία</orth>
                </form>
                <gram>ας, ἡ</gram>
                <etym>λούω</etym>
                <sense>
                    <def>bathing-time</def>
                    <bibl>Const.  Apost. 1, 9.</bibl>
                </sense>
            </entry>

            <entry>
                <form>
                    <orth>καιρός</orth>
                </form>
                <gram>ου, ο,</gram>

                <sense>
                    <def>time</def>
                    <cit>
                        <bibl>Aristot, Topic. 3, 2, 4</bibl>
                        <q>Ἐν παντί καιρῶ, at all times.</q>
                    </cit>
                    <cit>
                        <bibl>3, 2, 3</bibl>
                        <q> Ἕκαστον ἐν ᾧ καιρῷ μεῖζον δύναται, ἐν τούτῳ καὶ αἱρετώτερον.</q>
                    </cit>
                    <cit>
                        <bibl>Inscr. 3595, 16. 3137</bibl>
                        <q>Καθ’ ὃν καιρόν, at the time when, simply when.</q>
                    </cit>
                    <cit>
                        <bibl>Sept. Par. 1, 9, 25</bibl>
                        <q>"Από καιροῦ εις καιρόν, from time to time.</q>
                    </cit>
                    <cit>
                        <bibl>Sap. 4, 4 Ipés</bibl>
                        <q>καιρόν, for a time, temporarily.</q>
                    </cit>
                    <cit>
                        <bibl>Poly. 1, 7,6. 1,61, 4. 2, 57, 3.  4, 33, 8.  5, 56, 15.  5, 57, 10</bibl>
                        <q>Καθ’ οὑς καιρούς.</q>
                    </cit>
                    <cit>
                        <bibl>16, 3, 6</bibl>
                        <q>Έν ῶ καιρῶ, at which time, when.</q>
                    </cit>
                    <cit>
                        <bibl>27, 1, 1.</bibl>
                        <q>Κατὰ τοῦτον τὸν καιρόν, about this time.</q>
                    </cit>
                    <cit>
                        <bibl>Diod, 1, 19. 4, 185</bibl>
                        <q>Μέχρι τῶν καθ’ ἡμᾶς καιρῶν, down to our times.</q>
                    </cit>
                    <cit>
                        <bibl>13, 45</bibl>
